version: '1'

services:
  rstudio:
    image: zx2yizzy/dsci-310-group-8-project-docker:latest
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=group8  
      - USER=rstudio
    volumes:
      - .:/home/rstudio/project  # Mount current directory to /home/rstudio/project in container