services:
  rstudio:
    image: zx2yizzy/dsci-310-group-8-project-docker:latest
    platform: linux/amd64  # Add this for Apple Silicon compatibility
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=group8
      - USER=rstudio
    volumes:
      - .:/home/rstudio/project