version: '1'

services:
  rstudio:
    image: dsci-310-group-8-docker:latest
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=group8  
      - USER=rstudio
    volumes:
      - .:/home/rstudio/project