name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag michaeltham/dsci-310-group-08:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push  michaeltham/dsci-310-group-08:latest
